import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { ShoppingItem } from './entities/shopping-item.entity';
import { MealPlanItem } from '../meal-plan-items/entities/meal-plan-item.entity';
import { RecipeIngredient } from '../recipe-ingredients/entities/recipe-ingredient.entity';
import { PantryItem } from '../pantry-items/entities/pantry-item.entity';
import { CreateShoppingItemDto } from './dto/create-shopping-item.dto';
import { UpdateShoppingItemDto } from './dto/update-shopping-item.dto';

@Injectable()
export class ShoppingListService {
  constructor(
    @InjectRepository(ShoppingItem)
    private readonly shoppingItemRepository: Repository<ShoppingItem>,
    @InjectRepository(MealPlanItem)
    private readonly mealPlanItemRepository: Repository<MealPlanItem>,
    @InjectRepository(RecipeIngredient)
    private readonly recipeIngredientRepository: Repository<RecipeIngredient>,
    @InjectRepository(PantryItem)
    private readonly pantryItemRepository: Repository<PantryItem>,
  ) {}

  findAll(userId: string): Promise<ShoppingItem[]> {
    return this.shoppingItemRepository.find({
      where: { user: { id: userId } },
      order: { purchased: 'ASC', createdAt: 'ASC' },
    });
  }

  create(userId: string, dto: CreateShoppingItemDto): Promise<ShoppingItem> {
    const item = this.shoppingItemRepository.create({
      user: { id: userId },
      name: dto.name,
      quantity: dto.quantity,
      unit: dto.unit,
    });
    return this.shoppingItemRepository.save(item);
  }

  async update(
    userId: string,
    id: string,
    dto: UpdateShoppingItemDto,
  ): Promise<ShoppingItem> {
    const item = await this.findOwned(userId, id);
    Object.assign(item, dto);
    return this.shoppingItemRepository.save(item);
  }

  async remove(userId: string, id: string): Promise<{ id: string }> {
    const item = await this.findOwned(userId, id);
    await this.shoppingItemRepository.remove(item);
    return { id };
  }

  /**
   * Rebuild the user's shopping items for a meal plan: aggregate the ingredients
   * of every planned recipe, subtract current pantry stock, and upsert the
   * remainder. Merges duplicates (name+unit), preserves the `purchased` flag for
   * surviving rows, and drops rows the plan no longer needs.
   */
  async syncFromPlan(userId: string, mealPlanId: string): Promise<void> {
    // 1. Ingredients required by every recipe in the plan.
    const items = await this.mealPlanItemRepository.find({
      where: { mealPlanId },
    });
    const recipeIds = items.map((i) => i.recipeId);
    const ingredients = recipeIds.length
      ? await this.recipeIngredientRepository.find({
          where: { recipeId: In(recipeIds) },
        })
      : [];

    // 2. Total required per name+unit.
    const desired = new Map<
      string,
      { name: string; unit: string; quantity: number }
    >();
    for (const ing of ingredients) {
      const unit = (ing.unit ?? 'unit').trim();
      const key = `${ing.ingredientName.trim().toLowerCase()}|${unit.toLowerCase()}`;
      const qty = Number(ing.quantity ?? 0);
      const found = desired.get(key);
      if (found) found.quantity += qty;
      else desired.set(key, { name: ing.ingredientName, unit, quantity: qty });
    }

    // 3. Subtract pantry stock (matched by name+unit).
    const pantry = await this.pantryItemRepository.find({
      where: { user: { id: userId } },
    });
    for (const p of pantry) {
      const key = `${p.name.trim().toLowerCase()}|${p.unit.trim().toLowerCase()}`;
      const want = desired.get(key);
      if (want) {
        want.quantity -= Number(p.quantity);
        if (want.quantity <= 0) desired.delete(key);
      }
    }

    // 4. Reconcile against rows already generated by this plan (keep purchased).
    const existing = await this.shoppingItemRepository.find({
      where: { user: { id: userId }, mealPlan: { id: mealPlanId } },
    });
    const toSave: ShoppingItem[] = [];
    const toRemove: ShoppingItem[] = [];

    for (const row of existing) {
      const key = `${row.name.trim().toLowerCase()}|${row.unit.trim().toLowerCase()}`;
      const want = desired.get(key);
      if (want) {
        row.quantity = want.quantity;
        toSave.push(row);
        desired.delete(key);
      } else {
        toRemove.push(row);
      }
    }

    for (const want of desired.values()) {
      toSave.push(
        this.shoppingItemRepository.create({
          user: { id: userId },
          mealPlan: { id: mealPlanId },
          name: want.name,
          quantity: want.quantity,
          unit: want.unit,
          purchased: false,
        }),
      );
    }

    if (toRemove.length) await this.shoppingItemRepository.remove(toRemove);
    if (toSave.length) await this.shoppingItemRepository.save(toSave);
  }

  private async findOwned(userId: string, id: string): Promise<ShoppingItem> {
    const item = await this.shoppingItemRepository.findOne({
      where: { id, user: { id: userId } },
    });
    if (!item) {
      throw new NotFoundException('Shopping item not found');
    }
    return item;
  }
}
