import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ShoppingItem } from './entities/shopping-item.entity';
import { MealPlan } from '../meal-plans/entities/meal-plan.entity';
import { CreateShoppingItemDto } from './dto/create-shopping-item.dto';
import { UpdateShoppingItemDto } from './dto/update-shopping-item.dto';

@Injectable()
export class ShoppingListService {
  constructor(
    @InjectRepository(ShoppingItem)
    private readonly shoppingItemRepository: Repository<ShoppingItem>,
  ) {}

  findAll(userId: string): Promise<ShoppingItem[]> {
    return this.shoppingItemRepository.find({
      where: { user: { id: userId } },
      order: { purchased: 'ASC', createdAt: 'ASC' },
    });
  }

  create(userId: string, dto: CreateShoppingItemDto): Promise<ShoppingItem> {
    const item = this.shoppingItemRepository.create({
      user: { id: userId },
      name: dto.name,
      quantity: dto.quantity,
      unit: dto.unit,
    });
    return this.shoppingItemRepository.save(item);
  }

  async update(
    userId: string,
    id: string,
    dto: UpdateShoppingItemDto,
  ): Promise<ShoppingItem> {
    const item = await this.findOwned(userId, id);
    Object.assign(item, dto);
    return this.shoppingItemRepository.save(item);
  }

  async remove(userId: string, id: string): Promise<{ id: string }> {
    const item = await this.findOwned(userId, id);
    await this.shoppingItemRepository.remove(item);
    return { id };
  }

  /**
   * Fold a meal plan's per-dish shoppingList into the user's shopping_items.
   * Merges duplicates (same name+unit) and preserves the `purchased` flag for
   * items that survive an edit; removes items the plan no longer needs.
   */
  async syncFromPlan(userId: string, plan: MealPlan): Promise<void> {
    // 1. Merge desired items across all dishes, keyed by name+unit.
    const desired = new Map<
      string,
      { name: string; unit: string; quantity: number }
    >();
    for (const dish of plan.dishes ?? []) {
      for (const item of dish.shoppingList ?? []) {
        const key = `${item.name.trim().toLowerCase()}|${item.unit.trim().toLowerCase()}`;
        const found = desired.get(key);
        if (found) {
          found.quantity += Number(item.quantity);
        } else {
          desired.set(key, {
            name: item.name,
            unit: item.unit,
            quantity: Number(item.quantity),
          });
        }
      }
    }

    // 2. Reconcile against rows already generated by this plan.
    const existing = await this.shoppingItemRepository.find({
      where: { user: { id: userId }, mealPlan: { id: plan.id } },
    });
    const toSave: ShoppingItem[] = [];
    const toRemove: ShoppingItem[] = [];

    for (const row of existing) {
      const key = `${row.name.trim().toLowerCase()}|${row.unit.trim().toLowerCase()}`;
      const want = desired.get(key);
      if (want) {
        row.quantity = want.quantity; // keep purchased flag as-is
        toSave.push(row);
        desired.delete(key);
      } else {
        toRemove.push(row);
      }
    }

    // 3. Anything left in `desired` is brand new.
    for (const want of desired.values()) {
      toSave.push(
        this.shoppingItemRepository.create({
          user: { id: userId },
          mealPlan: { id: plan.id },
          name: want.name,
          quantity: want.quantity,
          unit: want.unit,
          purchased: false,
        }),
      );
    }

    if (toRemove.length) await this.shoppingItemRepository.remove(toRemove);
    if (toSave.length) await this.shoppingItemRepository.save(toSave);
  }

  private async findOwned(userId: string, id: string): Promise<ShoppingItem> {
    const item = await this.shoppingItemRepository.findOne({
      where: { id, user: { id: userId } },
    });
    if (!item) {
      throw new NotFoundException('Shopping item not found');
    }
    return item;
  }
}
